// Reconstructed from Chordie 1.1.2's static Chord catalogue. Order is significant.
// Constructor quality arguments of -1 leave the zero-initialized field unchanged,
// so interval entries use the runtime value 0 rather than the source sentinel -1.
export interface ChordieChordDefinition {
  name: string
  intervals: number[]
  qualityClass: number
  rootPositionOverride: number
  alternate: string
  checkForInversions: boolean
}

export const CHORDIE_CHORDS: ChordieChordDefinition[] = [
  { name: 'n.c.', intervals: [], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minor 2nd', intervals: [0, 1], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Major 2nd', intervals: [0, 2], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minor 3rd', intervals: [0, 3], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Major 3rd', intervals: [0, 4], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Perfect 4th', intervals: [0, 5], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Tritone', intervals: [0, 6], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Perfect 5th', intervals: [0, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minor 6th', intervals: [0, 8], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Major 6th', intervals: [0, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minor 7th', intervals: [0, 10], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Major 7th', intervals: [0, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Octave', intervals: [0, 12], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '', intervals: [0, 4, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min', intervals: [0, 3, 7], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim', intervals: [0, 3, 6], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Aug', intervals: [0, 4, 8], qualityClass: 4, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Sus2', intervals: [0, 2, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Sus4', intervals: [0, 5, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj(b5)', intervals: [0, 4, 6], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(no3)', intervals: [0, 7, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7(no3)', intervals: [0, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: 'Maj7', checkForInversions: true },
  { name: 'Maj7(no5)', intervals: [0, 4, 11], qualityClass: 0, rootPositionOverride: 0, alternate: 'Maj7', checkForInversions: true },
  { name: '7(no5)', intervals: [0, 4, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '7', checkForInversions: true },
  { name: 'min7(no5)', intervals: [0, 3, 10], qualityClass: 1, rootPositionOverride: 0, alternate: 'min7', checkForInversions: true },
  { name: '7sus4(no5)', intervals: [0, 5, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '7sus4', checkForInversions: true },
  { name: 'Maj(add2)', intervals: [0, 2, 4], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7', intervals: [0, 4, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7 Sus2', intervals: [0, 2, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7 Sus4', intervals: [0, 5, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '6/9', intervals: [0, 2, 4, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '6/9(no3)', intervals: [0, 2, 7, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj6', intervals: [0, 4, 7, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj6', intervals: [0, 3, 5, 8], qualityClass: 0, rootPositionOverride: 3, alternate: '', checkForInversions: true },
  { name: 'Maj6', intervals: [0, 2, 5, 9], qualityClass: 0, rootPositionOverride: 2, alternate: '', checkForInversions: true },
  { name: 'Maj9 no 5th', intervals: [0, 2, 4, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7b5', intervals: [0, 4, 6, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7#5', intervals: [0, 4, 8, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj(add2)', intervals: [0, 2, 4, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj(add b5)', intervals: [0, 4, 6, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj(add b5)', intervals: [0, 2, 3, 8], qualityClass: 0, rootPositionOverride: 3, alternate: '', checkForInversions: true },
  { name: '', intervals: [0, 1, 6, 10], qualityClass: 0, rootPositionOverride: 2, alternate: '', checkForInversions: true },
  { name: 'Maj(add b5)', intervals: [0, 5, 9, 11], qualityClass: 0, rootPositionOverride: 1, alternate: '', checkForInversions: true },
  { name: 'Maj7(13)', intervals: [0, 4, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7', intervals: [0, 3, 7, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7b5', intervals: [0, 3, 6, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9', intervals: [0, 3, 10, 2], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min6', intervals: [0, 3, 7, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min6', intervals: [0, 4, 6, 9], qualityClass: 1, rootPositionOverride: 3, alternate: '', checkForInversions: true },
  { name: 'min6', intervals: [0, 2, 5, 8], qualityClass: 1, rootPositionOverride: 2, alternate: '', checkForInversions: true },
  { name: 'min6/9', intervals: [0, 3, 9, 2], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7(4)', intervals: [0, 3, 5, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min(add4/11)', intervals: [0, 3, 5, 7], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min(add4/11)', intervals: [0, 2, 4, 9], qualityClass: 1, rootPositionOverride: 3, alternate: '', checkForInversions: true },
  { name: 'min(add4/11)', intervals: [0, 5, 8, 10], qualityClass: 1, rootPositionOverride: 1, alternate: '', checkForInversions: true },
  { name: 'min(add2)', intervals: [0, 2, 3, 7], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj7', intervals: [0, 3, 7, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj7(13)', intervals: [0, 3, 9, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7(13)', intervals: [0, 3, 10, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7', intervals: [0, 4, 7, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7b5', intervals: [0, 4, 6, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7#5', intervals: [0, 4, 8, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus4', intervals: [0, 5, 7, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus4(b9)', intervals: [0, 1, 5, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9sus4', intervals: [0, 5, 10, 2], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus2', intervals: [0, 2, 7, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus4(13)', intervals: [0, 10, 5, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(13 no5)', intervals: [0, 4, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7#9(no5)', intervals: [0, 3, 4, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7b9(no5)', intervals: [0, 1, 4, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(9)', intervals: [0, 2, 4, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(add4)', intervals: [0, 4, 5, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: 'dim7', intervals: [0, 3, 6, 9], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj(add b9)', intervals: [0, 1, 4, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim(Maj7)', intervals: [0, 3, 6, 11], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim(Maj7)', intervals: [0, 3, 8, 9], qualityClass: 3, rootPositionOverride: 3, alternate: '', checkForInversions: true },
  { name: 'dim(Maj7)', intervals: [0, 5, 6, 9], qualityClass: 3, rootPositionOverride: 2, alternate: '', checkForInversions: true },
  { name: 'dim(Maj7#5)', intervals: [0, 3, 8, 11], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '(add#9)', intervals: [0, 5, 8, 9], qualityClass: 0, rootPositionOverride: 1, alternate: '', checkForInversions: true },
  { name: '(add#9)', intervals: [0, 3, 4, 7], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '(#9)', intervals: [0, 1, 4, 9], qualityClass: 0, rootPositionOverride: 3, alternate: '', checkForInversions: true },
  { name: '6/9', intervals: [0, 2, 4, 7, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9', intervals: [0, 2, 4, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7(13)', intervals: [0, 4, 7, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9(13)', intervals: [0, 2, 4, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9(#5)', intervals: [0, 2, 4, 8, 11], qualityClass: 4, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9(b5)', intervals: [0, 2, 4, 6, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9sus4', intervals: [0, 5, 7, 11, 2], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '6/9(#11)', intervals: [0, 4, 9, 6, 2], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7(add #5)', intervals: [0, 4, 7, 11, 8], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7(#11)', intervals: [0, 4, 7, 11, 6], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj(add2,#11)', intervals: [0, 4, 7, 2, 6], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '6(#11)', intervals: [0, 4, 6, 7, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj7(b5#5)', intervals: [0, 4, 6, 8, 11], qualityClass: 4, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min(add2/4)', intervals: [0, 2, 3, 5, 7], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7(11)', intervals: [0, 3, 5, 7, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9', intervals: [0, 2, 3, 7, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9(11)', intervals: [0, 2, 3, 5, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min6/9', intervals: [0, 2, 3, 7, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min6/9/11', intervals: [0, 2, 3, 5, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min(Maj9)', intervals: [0, 2, 3, 7, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7b5(11)', intervals: [0, 3, 6, 10, 5], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9(b5)', intervals: [0, 3, 6, 10, 2], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min11(b5)', intervals: [0, 6, 10, 2, 5], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7b5(b13)', intervals: [0, 3, 6, 10, 8], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj7(9)', intervals: [0, 3, 7, 11, 2], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj9(11)', intervals: [0, 2, 3, 5, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj7(13)', intervals: [0, 3, 7, 9, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj9(13)', intervals: [0, 3, 9, 11, 2], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7(13)', intervals: [0, 3, 7, 9, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9sus4', intervals: [0, 5, 7, 10, 2], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9sus4(add3)', intervals: [0, 5, 10, 2, 4], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13sus', intervals: [0, 2, 5, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13sus(b9)', intervals: [0, 5, 10, 1, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9sus4(b13)', intervals: [0, 5, 10, 2, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus4(b9b13)', intervals: [0, 5, 10, 1, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus4(b9b3)', intervals: [0, 5, 10, 1, 3], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7sus4(b9)', intervals: [0, 5, 7, 10, 1], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(add11)', intervals: [0, 4, 5, 7, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '9', intervals: [0, 2, 4, 7, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9(13)', intervals: [0, 2, 4, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9(#11)', intervals: [0, 2, 4, 6, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9(#5)', intervals: [0, 2, 4, 8, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(#9)', intervals: [0, 4, 7, 10, 3], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(b9)', intervals: [0, 4, 7, 10, 1], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(#11)', intervals: [0, 4, 7, 10, 6], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(#9#5)', intervals: [0, 3, 4, 8, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(b9#9)', intervals: [0, 1, 3, 4, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(#9b5)', intervals: [0, 3, 4, 6, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(b9#5)', intervals: [0, 1, 4, 8, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(b9b5)', intervals: [0, 1, 4, 6, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13(b9)', intervals: [0, 1, 4, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13(#9)', intervals: [0, 3, 4, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13#11', intervals: [0, 4, 6, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9(13)', intervals: [0, 4, 7, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim7(9)', intervals: [0, 3, 6, 9, 2], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim7(11)', intervals: [0, 3, 6, 9, 5], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim7(add M7)', intervals: [0, 3, 6, 9, 11], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim7(add #5)', intervals: [0, 3, 6, 9, 8], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dimMaj7(9)', intervals: [0, 3, 6, 11, 2], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dimMaj7(11)', intervals: [0, 3, 6, 11, 5], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dimMaj9(#5)', intervals: [0, 3, 8, 11, 2], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9(13)', intervals: [0, 2, 4, 7, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj13(#11)', intervals: [0, 2, 4, 6, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9(#11)', intervals: [0, 2, 4, 6, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '6/9(#11)', intervals: [0, 4, 7, 2, 6, 9], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj9(b5#5)', intervals: [0, 2, 4, 6, 8, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9(11)', intervals: [0, 2, 3, 5, 7, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min(Maj9/13)', intervals: [0, 2, 3, 7, 9, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7b5(9,11)', intervals: [0, 3, 6, 10, 2, 5], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'minMaj11(13)', intervals: [0, 3, 9, 11, 2, 5], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: 'min9/11(Maj7)', intervals: [0, 2, 3, 5, 7, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9(13)', intervals: [0, 3, 7, 10, 2, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min9(11,13)', intervals: [0, 10, 2, 3, 5, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min6/9(11)', intervals: [0, 7, 2, 3, 9, 5], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min7b5(b9b13)', intervals: [0, 1, 3, 6, 10, 8], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9(13)#11', intervals: [0, 2, 4, 6, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13(b9#11)', intervals: [0, 4, 10, 1, 6, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(#9#11)', intervals: [0, 4, 10, 3, 6, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(#9)', intervals: [0, 4, 7, 10, 3, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '9(#5b5)', intervals: [0, 2, 4, 6, 8, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(b9#9b5)', intervals: [0, 4, 10, 1, 3, 6], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(b9#9#5)', intervals: [0, 4, 10, 1, 3, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7sus(b9#9b13)', intervals: [0, 5, 10, 1, 3, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(b9b5b13)', intervals: [0, 4, 10, 1, 6, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '9(13)', intervals: [0, 4, 7, 9, 10, 2], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13(b9)', intervals: [0, 7, 4, 10, 1, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7(#9#11)', intervals: [0, 7, 4, 10, 3, 6], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(b9#11)', intervals: [0, 7, 4, 10, 1, 6], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(b9#9)', intervals: [0, 7, 4, 10, 1, 3], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(#9#11b13)', intervals: [0, 4, 10, 3, 6, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '7b9b13(add5)', intervals: [0, 7, 4, 10, 1, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7#9b13(add5)', intervals: [0, 7, 4, 10, 3, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13sus', intervals: [0, 7, 5, 10, 2, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13sus4(add3)', intervals: [0, 5, 10, 2, 4, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13sus4(add3)', intervals: [0, 5, 10, 7, 4, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '13sus(b9)', intervals: [0, 7, 5, 10, 1, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim7(9/11)', intervals: [0, 3, 6, 9, 2, 5], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dimMaj7(9/11)', intervals: [0, 3, 6, 11, 2, 5], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dim7(11b13)', intervals: [0, 3, 6, 9, 5, 8], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'dimM9(#5)', intervals: [0, 3, 6, 8, 11, 2], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj13(#11)', intervals: [0, 2, 4, 6, 7, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Ionian(Sus4)', intervals: [0, 2, 4, 5, 7, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Maj13(b5#5)', intervals: [0, 2, 4, 6, 8, 9, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min13(9,11)', intervals: [0, 2, 3, 5, 7, 9, 10], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Melodic Minor', intervals: [0, 2, 3, 5, 7, 9, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'Harmonic Minor', intervals: [0, 2, 3, 5, 7, 8, 11], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: '9(13)#11', intervals: [0, 2, 4, 7, 6, 9, 10], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13sus4(add3)', intervals: [0, 5, 10, 7, 4, 2, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(b9#11)', intervals: [0, 4, 7, 10, 1, 6, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(b9#9#11)', intervals: [0, 4, 7, 10, 1, 3, 6], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7alt', intervals: [0, 4, 10, 1, 6, 8, 3], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(b9#9#11)', intervals: [0, 4, 10, 1, 3, 6, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(#9#11)', intervals: [0, 7, 4, 10, 3, 6, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7(b9#9b13)', intervals: [0, 7, 4, 10, 3, 8, 1], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7sus(b9#9b13)', intervals: [0, 5, 7, 10, 1, 3, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: 'dim(add M7,9,11)', intervals: [0, 3, 6, 9, 11, 2, 5], qualityClass: 3, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(b9#9#11)', intervals: [0, 4, 7, 10, 1, 3, 6, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7alt(add5)', intervals: [0, 7, 4, 10, 1, 3, 6, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(b9#9)', intervals: [0, 4, 10, 3, 7, 9, 1], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(b9#9)', intervals: [0, 4, 10, 1, 3, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '13(b9#9)', intervals: [0, 4, 10, 1, 3, 7, 9], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: '7b9#11b13', intervals: [0, 4, 7, 10, 1, 6, 8], qualityClass: 2, rootPositionOverride: 0, alternate: '', checkForInversions: false },
  { name: 'Maj9#11(no3)', intervals: [0, 2, 6, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'SusMaj7(add3)', intervals: [0, 4, 5, 7, 11], qualityClass: 0, rootPositionOverride: 0, alternate: '', checkForInversions: true },
  { name: 'min13(no9)', intervals: [0, 3, 10, 5, 9], qualityClass: 1, rootPositionOverride: 0, alternate: '', checkForInversions: true },
]
